_target_: models.lit_module.LitModule

batch_size: 256
num_workers: 4 # 4*n_gpus
pin_memory: True
n_classes: 11

backbone:
  _target_: models.components.airgnn_backbone.Backbone
  hidden_dim: 64
  hidden_dim_ffnn: 1024
  n_classes: 11
  k: 5
  snr_db: 40
  p: .3
  delta: 0.707

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10