program: src/train.py
args_no_hyphens: False
method: grid
metric:
  name: val/acc
  goal: minimize
parameters:
  model:
    values: [tnn, gnn]
  seed:
    values: [0,1,2,3,4]
  model.backbone.snr_db:
    values: [-10,0,10,20,40]
  model.backbone.delta:
    values: [1]
  trainer.max_epochs:
    values: [100]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}