program: src/train.py
args_no_hyphens: False
method: grid
metric:
  name: val/acc
  goal: minimize
parameters:
  model.backbone.hidden_dim:
    values: [64,128]
  model.backbone.k:
    values: [1,3,5]
  model.optimizer.lr:
    values: [0.01,0.001]
  model.batch_size:
    values: [128,256]
  

# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 10

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}