program: src/train.py
args_no_hyphens: True
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  net.c_out:
    values: [8,16,32,64,128]
  net.k:
    values: [1,2,3,4,5]
  net.snr_db:
    values: [10,20,30,40,50,60,70,80,90,100]
  net.optimizer.lr:
    values: [0.001,0.0001,0.00001]
  net.optimizer.weight_decay:
    values: [0,0.9,0.99,0.999]
  datamodule.batch_size:
    values: [16,32,64,128]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 10


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}