program: src/train.py
args_no_hyphens: True
method: random
metric:
  name: val/loss
  goal: minimize
parameters:
  net.backbone.hidden_dim:
    values: [8,16,32,64,128,256,512]
  # net.optimizer.lr:
  #   values: [0,01,0.001,0.0001]
  # net.optimizer.weight_decay:
  #   values: [0,0.9]
  datamodule.batch_size:
    values: [16,32,64,128]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 5

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}