program: src/train.py
args_no_hyphens: False
method: grid
metric:
  name: val/acc
  goal: minimize
parameters:
  model:
    values: [airtnn,airgnn]
  model.backbone.hidden_dim:
    values: [64,32,16]
  model.backbone.k:
    values: [1,5]
  model.backbone.p:
    values: [.0,.3]
  model.backbone.snr_db:
    values: [100,80]
  model.batch_size:
    values: [128]
  

# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 10

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}