program: src/train.py
args_no_hyphens: False
method: random
metric:
  name: val/acc
  goal: minimize
parameters:
  model.backbone.hidden_dim:
    values: [128,256,512]
  model.backbone.k:
    values: [1,2,3,4,5]
  model.backbone.p:
    values: [0,0.1,0.2,0.3,0.4,0.5]
  model.optimizer.weight_decay:
    values: [0,0.001]
  datamodule.batch_size:
    values: [128,256,512]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 10

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}