task_name: "train"

defaults:
  - _self_
  - callbacks: default
  - paths: default
  - hydra: default
  - trainer: gpu
  - model: airtnn
  - datamodule: cell_sbm
seed: 42
logger:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  save_dir: "logs"
  offline: True # <---------------------------------------------------------------------------------------
  id: null # pass correct id to resume experiment!
  project: "airtnn"
  log_model: False # upload lightning ckpts
  group: "signal_diffusion"
  tags: ['05/10', 'grid_sweep'] # <---------------------------------------------------------------------------------------
  notes: "testing"
  job_type: ""