task_name: "train"
defaults:
  - _self_
  - callbacks: default
  - paths: default
  - hydra: default
  - trainer: gpu
  - model: airtnn # <---------------------------------------------------------------------------------------
  - datamodule: cell_sbm
logger:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  save_dir: "logs"
  offline: True # <---------------------------------------------------------------------------------------
  id: null # pass correct id to resume experiment!
  project: "ICASSP24" 
  log_model: False # upload lightning ckpts
  group: ""
  tags: [] # <---------------------------------------------------------------------------------------
  notes: "paper_simulation"
  job_type: ""

seed: 42

dataset:
  _target_: data.cell_sbm_dataset.CellDataset
  n_nodes: 70 
  n_community: 10 
  p_intra: 0.9 
  p_inter: 0.01
  num_samples: 15000 
  k_diffusion: 50
  spike: 1
  snr_db: 40
  n_spikes: .85
  shift_flag: 'edge_adj'
  ntype: identity # 'spectral', 'identity'