task_name: "train"

defaults:
  - _self_
  - callbacks: default
  - paths: default
  - hydra: default
  - trainer: gpu
  - model: airgnn
  - datamodule: sbm
seed: 42
logger:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  save_dir: "logs"
  offline: False # <---------------------------------------------------------------------------------------
  id: null # pass correct id to resume experiment!
  project: "airgnn"
  log_model: False # upload lightning ckpts
  group: "signal_diffusion"
  tags: ['04/28'] # <---------------------------------------------------------------------------------------
  notes: "testing"
  job_type: ""